[tool.pylint.messages_control]
max-line-length=88
disable=["missing-module-docstring", "line-too-long", "too-many-arguments", "unused-argument", "unused-import",
"missing-function-docstring", "pointless-string-statement"]

[tool.black]
target-version = ["py39"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
